---
- block:
  - name: Template the filebeat.yml
    ansible.builtin.template:
      src: filebeat.yml.j2
      dest: /etc/filebeat/filebeat.yml
      owner: root
      group: root
      mode: 0755

  - name: Template the ossec.conf
    ansible.builtin.template:
      src: ossec.conf.j2
      dest: /var/ossec/etc/ossec.conf
      owner: root
      group: root
      mode: 0755

  # keystore location: /var/lib/filebeat/filebeat.keystore
  - name: Create a Filebeat keystore to securely store authentication credentials
    ansible.builtin.shell:
      cmd: filebeat keystore create --force

  - name: Add the default username to the secrets keystore.
    ansible.builtin.shell:
      cmd: echo admin | filebeat keystore add username --stdin --force

  - name: Add the default password to the secrets keystore.
    ansible.builtin.shell:
      cmd: echo admin | filebeat keystore add password --stdin --force

  - name: Copy the alerts template for the Wazuh indexer
    ansible.builtin.copy:
      src: ./files/wazuh-template.json
      dest: /etc/filebeat/wazuh-template.json
      owner: root
      group: root
      mode: 0644

  - name: Extract the wazuh-filebeat-0.4.tar.gz (Wazuh module for Filebeat.)
    ansible.builtin.unarchive:
      src: ./files/wazuh-filebeat-0.4.tar.gz
      dest: /usr/share/filebeat/module/
      owner: root
      group: root
      mode: 0750

  # Configuring the Wazuh indexer connection
  - name: Save the Wazuh indexer username into the Wazuh manager keystore using the wazuh-keystore tool
    ansible.builtin.shell:
      cmd: echo 'admin' | /var/ossec/bin/wazuh-keystore -f indexer -k username

  # Configuring the Wazuh indexer connection
  # learning purposes, draft, we do not care about the dummy credentials
  - name: Save the Wazuh indexer password into the Wazuh manager keystore using the wazuh-keystore tool
    ansible.builtin.shell:
      cmd: echo 'Str?wberrypie94' | /var/ossec/bin/wazuh-keystore -f indexer -k password

  - name: Ensure filebeat works as expected
    ansible.builtin.shell:
      cmd: filebeat test output

  - name: Disabling the Wazuh package repositories after installing all components
    ansible.builtin.shell:
      cmd: 'sed -i "s/^deb /#deb /" /etc/apt/sources.list.d/wazuh.list'

  - name: Refresh known packages
    ansible.builtin.apt:
      update_cache: yes

  - name: Reload and restart wazuh-manager.service
    ansible.builtin.systemd:
      name: wazuh-manager.service
      state: restarted
      daemon_reload: yes
      enabled: yes

  - name: Template the wazuh.yml
    ansible.builtin.template:
      src: wazuh.yml.j2
      dest: /etc/filebeat/modules.d/wazuh.yml
      owner: root
      group: root
      mode: 0755

  - name: Enable and restart filebeat.service
    ansible.builtin.systemd:
      name: filebeat.service
      state: restarted
      enabled: yes

  - name: Enable and restart wazuh-manager.service
    ansible.builtin.systemd:
      name: wazuh-manager.service
      state: restarted
      enabled: yes

  # learning purposes, draft, we do not care about the dummy credentials
  - name: Create index template manually
    ansible.builtin.shell:
      cmd: "curl -X PUT 'https://aws-dummy-ops-wazuh-indexer.lab:9200/_template/wazuh' \
        -H 'Content-Type: application/json' \
        -d@/etc/filebeat/wazuh-template.json \
        -u admin:Str?wberrypie94"
  become: yes
