upstream aws-dummy-ops-jenkins.lab {
  server aws-dummy-ops-jenkins.lab:8443;
}

server {
    listen 80;
    server_tokens off;
    server_name aws-dummy-ops-nginx.lab;
    return 301 https://$host$request_uri;
}

server {
    # Debian13 syntax
    # listen 443 ssl;
    # http2 on;
    # Debian12 syntax
    listen 443 ssl http2;
    server_name aws-dummy-ops-nginx.lab aws-dummy-ops-nginx-jenkins-proxy-client.lab;
    server_tokens off;
    ssl_dhparam /etc/nginx/secrets/dhparam.pem;
    ssl_certificate /etc/nginx/secrets/aws_dummy_ops_nginx_jenkins.crt;
    ssl_certificate_key /etc/nginx/secrets/aws_dummy_ops_nginx_jenkins.key;
    ssl_trusted_certificate /etc/nginx/secrets/aws_dummy_ops_nginx_jenkins_fullchain.crt;
    ssl_protocols TLSv1.3;
    ssl_prefer_server_ciphers on;
    ssl_ciphers HIGH:!aNULL:!MD5;
    ssl_ecdh_curve secp384r1;
    ssl_session_timeout 10m;
    ssl_session_cache shared:SSL:10m;
    ssl_session_tickets off;
    ssl_stapling on;
    ssl_stapling_verify on;

    add_header Strict-Transport-Security "max-age=31536000; includeSubDomains; preload";
    add_header X-Frame-Options "SAMEORIGIN" always;
    add_header X-Content-Type-Options nosniff always;
    add_header X-XSS-Protection "1; mode=block" always;

    location / {
        proxy_pass https://aws-dummy-ops-jenkins.lab;
        proxy_ssl_certificate /etc/nginx/secrets/aws_dummy_ops_nginx_jenkins_proxy_client.crt;
        proxy_ssl_certificate_key /etc/nginx/secrets/aws_dummy_ops_nginx_jenkins_proxy_client.key;
        proxy_ssl_trusted_certificate /etc/nginx/secrets/aws_dummy_ops_nginx_jenkins_proxy_client_fullchain.crt;
	      proxy_ssl_verify on;
        proxy_ssl_verify_depth 2;
        proxy_ssl_session_reuse on;
        proxy_ssl_protocols TLSv1.2 TLSv1.3;
        proxy_ssl_ciphers HIGH:!aNULL:!MD5;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header Host $host;
        proxy_buffering off;
        proxy_redirect off;
        client_max_body_size 1M;
    }

    # Webhook Location Block
    location /github-webhook/ {
        proxy_pass https://aws-dummy-ops-jenkins.lab/github-webhook/;

        # SSL Handling for internal communication (with self-signed certs)
        proxy_ssl_certificate /etc/nginx/secrets/aws_dummy_ops_nginx_jenkins_proxy_client.crt;
        proxy_ssl_certificate_key /etc/nginx/secrets/aws_dummy_ops_nginx_jenkins_proxy_client.key;
        proxy_ssl_trusted_certificate /etc/nginx/secrets/aws_dummy_ops_nginx_jenkins_proxy_client_fullchain.crt;

	      proxy_ssl_verify on;
        proxy_ssl_session_reuse on;
        proxy_ssl_protocols TLSv1.2 TLSv1.3;
        proxy_ssl_ciphers HIGH:!aNULL:!MD5;

        # Headers for passing the correct information
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header Host $host;

	      # Ensure the entire request body is forwarded correctly
        proxy_set_header Content-Length $content_length;
        proxy_set_header X-Real-IP $remote_addr;

        # Other proxy settings
        proxy_buffering off;
        proxy_redirect off;
        client_max_body_size 2M;
	      proxy_read_timeout 300;
    }
}
