---
- hosts: 'k8s'
  become: true
  become_user: devops
  gather_facts: false
  tasks:
    - name: Deploy the dummy-app on kubernetes
      ansible.builtin.command:
        cmd: 'kubectl apply -f dummy_deployment.yml'

    - name: Start the kubernetes service attached to the dummy-app
      ansible.builtin.command:
        cmd: 'kubectl apply -f dummy_service.yml'
