---
jenkins_public_ip: '35.180.87.197'
jenkins_private_ip: '172.31.34.116'
tomcat_public_ip: '13.38.55.5'
tomcat_private_ip: '172.31.10.208'
docker_public_ip: '35.180.65.119'
docker_private_ip: '172.31.4.11'
ansible_public_ip: '51.44.222.118'
ansible_private_ip: '172.31.15.27'
k8s_public_ip: '13.39.86.118'
k8s_private_ip: '172.31.40.77'
nginx_public_ip: '15.237.111.24'
nginx_private_ip: '172.31.14.95'
wazuh_dashboard_public_ip: '35.181.4.75'
wazuh_dashboard_private_ip: '172.31.5.99'
wazuh_indexer_public_ip: '15.224.18.252'
wazuh_indexer_private_ip: '172.31.2.165'
wazuh_server_public_ip: '52.47.164.231'
wazuh_server_private_ip: '172.31.1.96'

AWS_REGION: "{{ lookup('env', 'AWS_REGION') }}"
GITHUB_USERNAME: "{{ lookup('env', 'GITHUB_USERNAME') }}"
GITHUB_REPO_NAME: "{{ lookup('env', 'GITHUB_REPO_NAME') }}"
DOCKERHUB_USERNAME: "{{ lookup('env', 'DOCKERHUB_USERNAME') }}"
DOCKERHUB_REPO_NAMESPACE: "{{ lookup('env', 'DOCKERHUB_REPO_NAMESPACE') }}"
NGINX_AWS_SECRET_ID_NAME: "{{ lookup('env', 'NGINX_AWS_SECRET_ID_NAME') }}"
ANSIBLE_SSH_KEY_FILENAME: "{{ lookup('env', 'ANSIBLE_SSH_KEY_FILENAME') }}"
ANSIBLE_AWS_SECRET_ID_NAME: "{{ lookup('env', 'ANSIBLE_AWS_SECRET_ID_NAME') }}"
JENKINS_SSH_KEY_FILENAME: "{{ lookup('env', 'JENKINS_SSH_KEY_FILENAME') }}"
JENKINS_AWS_SECRET_ID_NAME: "{{ lookup('env', 'JENKINS_AWS_SECRET_ID_NAME') }}"
JENKINS_KEYSTORE_PASSPHRASE: "{{ lookup('env', 'DOCKERHUB_REPO_NAMESPACE') }}"
TOMCAT_HTTPS_KEYSTORE_PASSWORD: "{{ lookup('env', 'TOMCAT_HTTPS_KEYSTORE_PASSWORD') }}"
TOMCAT_AWS_SECRET_ID_NAME: "{{ lookup('env', 'TOMCAT_AWS_SECRET_ID_NAME') }}"
TOMCAT_DEPLOYER_CREDENTIAL_ID: "{{ lookup('env', 'TOMCAT_DEPLOYER_CREDENTIAL_ID') }}"
TOMCAT_DEPLOYER_USERNAME: "{{ lookup('env', 'TOMCAT_DEPLOYER_USERNAME') }}"
TOMCAT_DEPLOYER_PASSWORD: "{{ lookup('env', 'TOMCAT_DEPLOYER_PASSWORD') }}"
DOCKER_TOMCAT_KEYSTORE_PASSPHRASE: "{{ lookup('env', 'DOCKER_TOMCAT_KEYSTORE_PASSPHRASE') }}"
JENKINS_CREDENTIALS_ID: "{{ lookup('env', 'JENKINS_CREDENTIALS_ID') }}"
JENKINS_ADMIN_USER_USERNAME: "{{ lookup('env', 'JENKINS_ADMIN_USER_USERNAME') }}"
JENKINS_ADMIN_USER_PASSWORD: "{{ lookup('env', 'JENKINS_ADMIN_USER_PASSWORD') }}"
JENKINS_SSH_PRIVATE_KEY: |
  -----BEGIN RSA PRIVATE KEY-----
  Proc-Type: 4,ENCRYPTED
  DEK-Info: AES-128-CBC,DFEC3272FF7730FE10A73A17911C23D2
  
  Y7a8cvV8QvXRS+DqWIGEsHFn08sdLXJZUqMLe5Zy89OIr1hDkY/c6QTxKa01SHuq
  /2Et7UDVoUjvnw6F7hugOLkD4RCVgTFDioexAHpJtG7h+PpP1ZPVvd23rufpq5k3
  7DpjU+/RDR6oxlcqTAaOSe7SDT8g2NXnm13Wb9dToVhjDZ8qKLGF5eJ3vGIcDhkA
  hs46Y5TiUOfr3kH6EDRhF16v2l8VBs7iskI0I08lZLtMFHTCrSG3kFmxwOnpQvqs
  VXWoQITma4PcDHNfl4x/nbWR2anUyFi3tX22ActP6KTy7gOcYNXoroXYsJ2YAHzg
  cONuX3lAJIt5k3QpvjmZJ1Sn5fhvXEPlSFuN+vKQ/+IT/iAATvdhMB448b6dK6W6
  rKyH+LYmoLbU0+M61XtAoNJ/E9tJpbivtNCnu2732ouh57GUW27ERJUwOdwW3P2n
  Sfp2rRJt81uvOEj20s2+7BejWQ8GaB+Tm/fwqIPsES25+DdVs71E06fMARks/AI0
  zbxkUMN4nrM2qVJRZuP1sXUKxD6sFXKHHQDgFNwyGlusgFp/zHKyW5b5Qbl4FkVp
  I1vvngEsqMT+eub9byM0CtAPtwE29GC6pnIPzwK2egMST92eb9+tIs3IBpSaJiD7
  ZqGKr7jQISCRaH7utBH4xpXyTZL0bt9dAaUPV3DDrmrhGXCbj8hUkYHddKDxrYaA
  57loABeaZLKxRfCzXN96pkuNdwqmqWje+zQrNKOpSmkpBuG0CjjGy5mlcvqlcpXI
  AEsISMSfI5/k1NT8mXqTr8QsIkn5aRGIYG0ZVkyF4ZCwUZE+sZqiCQur8IOl3sWS
  lFv5BnmD/xx60eiHo3SbFazF+fhEaoz+OD6hMIS+snTYclXto0LSHwpt9UDCy+7k
  6mxcui9xDDPQflIUMtUSXJvF4g2dHhEiK214s+kb0FzbO6ls2Rr6Q3lpMAwGJZ/w
  2kqSMGClKUufxPK5ZtgXdGtzp6s+6N17yhwp29Ex3IKMvqoaQ0MRYS4P200fJ5Ey
  CtfePzYBQZ356V7sNU1eVvXc5V3apZvQobmipYw1FwUH6jAWDm6bMZYOdc4ufj30
  AnQPBuq+j6+sX0JEQ7jPljJsTH3WFECEG1qQV8W9EMTTHwmwZo2GSwZOJRKPDta9
  fH3nTb6kLrQWgQClWb4EutLhd/ymc2KaNvSu5krJYHc3AtbAaOYYrYSUCGUPTtLK
  Am5/h8AFt0P//wOvlNqxko8B5JcxA89ogseqXLPG4LlR5cBZU5kJbGIAZSECuAEH
  iVW92fpvb3CXAzH4EhX9nLpRmExJII8hqfYdPje5yR/w3z6Ipjqb2ct7YkK2i1RM
  yXj8b3GGn0R+XdFU/IJLrgUxPHiTeqYKcAZjJ3EGAOAsxjBQfUm9/uDmvBPTBQB0
  4uvIpXZqGZf3Y4OR9FQGW7M3KAciZkZn6qRJ9nRU6zspyYgdMJpKI5varTj4Y3M1
  DEJpPcnwgnSoqHwjwOLzGqTQeWCGbzGMtp0oS6J2Iv/mAnPSy8HUiiSac8Sf7FmP
  mL5NYWByFl4k+GzCOjiu1Bm+/vLkv9cqK7STGL/K9VNKDEKfdCWuygKWZETbAxVn
  sKTKd+lrfPpBw2q+HpnUAkeoA9tjioqm4vS1ySnKV78mpz7Vm+/Jw3HDbSBDA7Az
  oH39n5kXjmyXeFC/IUq3HZbI9oYulPX+OQNNdnvmGIsETVOkUz67wBhPZdhw6hI/
  5/U4wXJSY0YTZ4Mju7L/9WToY0Jb+7vSXeBVdZcJX+qW/ogXgHdjyT04XdJ/IvEQ
  AQtFy6MKZSMOR8haINIYwkiKKbWucL8FJQ0XEm4a5cuSYP4xHxtwFmr5q6r3jG80
  qJL0fVaqKMj5BHt9j9oBS07r1qshlPDnqpJUdB6GxvPaYJuSldpUtBbNGi6hDHuU
  Uqpe/LYbi2w5oNZnN7Ii1MetHDCl4umYUmXwFh2GVe+fuIMaTV2nitstv4fQ4oWA
  lXYSewVbWqv0f+5uPMMlWU1WRVHDwRq5s9A/h4N4HbAZ/8dr6XJIL1tZeu9MTXzR
  AwWXfBN+LKd/DvxQij/JeXboFlc7gZztfxmYr4YlpkRuBFJoCnbGKBIoNTCp7mum
  qSjhsMd2IALgLSWX2Zhx0XC1HkIKL33Dt6n6EPGnb5RAk69cmREN0ERE2UJuNjYd
  scpgt694c7m8N8TQOZyvA0jniwGRLlxEWvwGd9r6o7Wh1lWJCOffYDF2ZkeFQ99z
  nSS/DShzVpwVOn3lOaEAzKwhxwzylkmO+pBGRt0IybnWOX9v5R1CFIC2OaEigl9P
  DLQiokwKih8CihdHJrUrT7kngIoPm3g+QJ+ZhJAuXMTGd1VoILOeLydWQ+1Qwo3Y
  7R4czaDluS4gah6d3a6JFe/S7rDx/f8xlcS6mPlL/dm/ICplJB8N4U1Nhq1feTGk
  9GXS1uyoDJ42d10HpE4Zt0MJ1FrGhmeghPnm6srh5QoBykGzCe391PhDApn2TpKZ
  AKrwFKzSojOrCGeyanF+g3UQwEd0bPIjQcCY5i+imml+LTtL9NXzl8aFw8j/w1Hi
  a+Q675rNmmEjiqkGomxf6x0KuXP+Z0i5DqMDBD8fp9VsoUItnQgtNb4DH3BKPd7f
  PJuUkQwZHIelmz7Pdv3c04OpLnPYWeE2Xq8eGLf9GzxErCTixH89EJLmowLFpzTV
  H8yU+3FdO8ENvWU3sphfAbZbtWE+1OI4ZUmSZu0i4uvmq7SxSMifmd5kF/0Ddfgn
  FI11Lh5G5GkVQ70zqDUMtfu7ibaxWnR4r1VmtkNnvwCHv3xQXqaMKqcju4dX9Rlz
  cO1zHRrvceSlqLxcLJXyuwAQUgyQ/Eay7evqaenLy/r9BpjPjVskQ54PQKn3sS7O
  IV+/TAA/siWgQzx6AcAebV2cAUS6O3bfEsyqoqhsfwQeZXTge6gOeejQ81ohZN5D
  iTZystnWcwGoOd8iPL/nYF7As+VsvUVSRBjinP5FY4D1rhSG83iLcJpCeAjOZtIf
  uBmOX7XLTBmVl9m5AJKu+yhYyWI2ReiU4jRfwRYOVBwhMCNTbsQ+HaQh4VQm34rp
  jI1Z0Q2Za99qB5WnbqtQMtVpE0wsb87/m45SLB5YpApuxu3gPUYATJHB1SGtJnmS
  -----END RSA PRIVATE KEY-----
