[active]
jenkins ansible_host=35.180.87.197 ansible_user=admin ansible_ssh_private_key_file=~/.ssh/aws_2025_devops/aws_terraform_remote_exec_key ansible_python_interpreter=/opt/jenkins-venv/bin/python
tomcat ansible_host=13.38.55.5 ansible_user=admin ansible_ssh_private_key_file=~/.ssh/aws_2025_devops/aws_terraform_remote_exec_key
docker ansible_host=35.180.65.119 ansible_user=admin ansible_ssh_private_key_file=~/.ssh/aws_2025_devops/aws_terraform_remote_exec_key
k8s ansible_host=15.224.176.25 ansible_user=admin ansible_ssh_private_key_file=~/.ssh/aws_2025_devops/aws_terraform_remote_exec_key
ansible ansible_host=51.44.222.118 ansible_user=admin ansible_ssh_private_key_file=~/.ssh/aws_2025_devops/aws_terraform_remote_exec_key
nginx ansible_host=15.237.111.24 ansible_user=admin ansible_ssh_private_key_file=~/.ssh/aws_2025_devops/aws_terraform_remote_exec_key
wazuh_dashboard ansible_host=35.181.4.75 ansible_user=admin ansible_ssh_private_key_file=~/.ssh/aws_2025_devops/aws_terraform_remote_exec_key
wazuh_server ansible_host=52.47.164.231 ansible_user=admin ansible_ssh_private_key_file=~/.ssh/aws_2025_devops/aws_terraform_remote_exec_key
wazuh_indexer ansible_host=15.224.18.252 ansible_user=admin ansible_ssh_private_key_file=~/.ssh/aws_2025_devops/aws_terraform_remote_exec_key
